# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  node: circleci/node@1.0.1

workflows:
  version: 2

  review:
    jobs:
      - build

jobs:
  build:
    executor: node/default
    working_directory: ~/react-turn-reveal

    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn i
            - run: yarn run lint
            - run: yarn run test
            - run: yarn run build
            - run: npx docz build
