# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  node: circleci/node@1.1.4

workflows:
  version: 2

  review:
    jobs:
      - build
      - "build docs"
#      - test:
      - lint

environment: &environment
  docker:
    - image: cdfa/cci-react-turn-reveal-primary:1.0.3
  working_directory: &working_directory ~/react-turn-reveal

attach_workspace: &attach_workspace
  attach_workspace:
    at: *working_directory

install_dependencies: &install_dependencies
  node/with-cache:
    dir: ~/.pnpm-store
    cache-version: v2
    steps:
      - node/with-cache:
          cache-version: v3
          steps:
            - run: pnpm i

jobs:
  build:
    <<: *environment
    steps:
      - checkout
      - *install_dependencies
      - run: npm run -s build

  lint:
    <<: *environment
    steps:
      - checkout
      - *install_dependencies
      - run: npm run -s lint

#  test:
#    <<: *environment
#    steps:
#      - checkout
#      - *attach_workspace
#      - run: pnpm i --shamefully-flatten jest-junit
#      - run:
#          command: npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit
#          environment:
#            JEST_JUNIT_OUTPUT: "reports/jest/js-test-results.xml"
#            CI: true
#      - store_test_results:
#          path: reports

  "build docs":
    <<: *environment
    steps:
      - checkout
      - *install_dependencies
      - run: npx docz build

