# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  node: circleci/node@1.0.1

workflows:
  version: 2

  review:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cdfa/cci-react-turn-reveal-primary:1.0.0
    working_directory: ~/react-turn-reveal

    steps:
      - checkout
      - node/with-cache:
          dir: ~/.pnpm-store
          cache-version: v2
          steps:
            - node/with-cache:
                cache-version: v3
                steps:
                  - run: pnpm i --shamefully-flatten
                  - run: npm run lint
                  - run: npm run build
                  - run: npm run test
                  - run: npx docz build
